Repository GregTechCE/GregTech, pull requests merged in 2020-08, with the labels that each got.

#1176 Bugfix/unification concurrent modification exception
  src/main/java/gregtech/api/unification/OreDictUnifier.java
  src/main/java/gregtech/common/ConfigHolder.java
Labels: subsystem: config, type: bug

#1178 Bugfix/bone meal and blaze powder inconsistency
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/loaders/OreDictionaryLoader.java
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
Labels: subsystem: recipes, type: bug

#1186 Bugfix/crafting station jei integration + other fixes
  src/main/java/gregtech/api/gui/ModularUI.java
  src/main/java/gregtech/api/gui/Widget.java
  src/main/java/gregtech/api/gui/impl/ModularUIGuiHandler.java
  src/main/java/gregtech/api/gui/widgets/AbstractWidgetGroup.java
  src/main/java/gregtech/api/gui/widgets/ScrollableListWidget.java
  src/main/java/gregtech/api/gui/widgets/TabGroup.java
  src/main/java/gregtech/common/gui/widget/ItemListGridWidget.java
  src/main/java/gregtech/common/metatileentities/storage/CraftingRecipeResolver.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
Labels: subsystem: integration/jei, type: bug

#1189 Feature/crystal battery boost
  src/main/java/gregtech/common/items/MetaItem2.java
  src/main/resources/assets/gregtech/recipes/nano_saber.json
Labels: subsystem: recipes, type: feature

#1188 Bugfix/duplicated block shapeless recipes
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/api/unification/material/type/DustMaterial.java
  src/main/java/gregtech/loaders/oreprocessing/MaterialRecipeHandler.java
Labels: subsystem: recipes, type: bug

#1185 Cleanup the Config file
  src/main/java/gregtech/common/ConfigHolder.java
Labels: status: accepted, subsystem: config

#1193 Bugfix/crash on getHarvestLevel when IBlockState is not provided
  src/main/java/gregtech/api/items/toolitem/ToolMetaItem.java
Labels: type: bug, type: multi mod interaction

#1194 Feature/facade output based on plate used
  src/main/java/gregtech/integration/jei/recipe/FacadeRegistryPlugin.java
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
Labels: subsystem: integration/jei, subsystem: recipes, type: feature

#1198 Feature/integrated circuit crafted with zero configuration
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
Labels: subsystem: recipes, type: feature

#1197 Bugfix/API shading + facade conflict
  build.gradle.kts
  build.properties
  src/main/java/cofh/core/render/IBlockAppearance.java
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/api/render/IBlockAppearance.java
  src/main/java/gregtech/common/covers/facade/FacadeBlockAccess.java
  src/main/java/gregtech/integration/ctm/IFacadeWrapper.java
  src/main/java/team/chisel/ctm/api/IFacade.java
Labels: subsystem: integration, subsystem: render, type: bug, type: multi mod interaction

#1205 Utils/readme update
  README.md
Labels: status: help needed

#1227 Bugfix/autoclave zh localization error
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: subsystem: internationalization/localization, type: bug

#1225 Bugfix/disabling rubber tree generation will also disable abandon base generation
  src/main/java/gregtech/GregTechMod.java
Labels: subsystem: config, type: bug

#1214 Scanner tooltip clarification
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: status: accepted, type: bug

#1213 Update zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: status: accepted, subsystem: internationalization/localization

#1204 Added english fruit juice localization
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: status: accepted, subsystem: internationalization/localization, type: bug

#1208 Fix JEI ghost items/fluids.
  src/main/java/gregtech/api/gui/widgets/PhantomFluidWidget.java
  src/main/java/gregtech/api/gui/widgets/PhantomSlotWidget.java
Labels: status: accepted, type: bug
