Repository GregTechCE/GregTech, pull requests merged in 2020-07, with the labels that each got.

#1108 Add minimum tier required to JEI information.
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/java/gregtech/integration/jei/utils/JEIHelpers.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: status: release blocker, subsystem: integration/jei, subsystem: recipes, type: feature

#1118 Render JEI recipe info from the bottom instead of at a constant height.
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
Labels: subsystem: integration/jei, type: feature

#1130 Fixed block drops for Thermal Foundation hammers
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/common/blocks/surfacerock/BlockSurfaceRockNew.java
Labels: status: accepted, type: bug, type: multi mod interaction

#1133 Unify the zh_cn translations for fluid_extractor
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: subsystem: internationalization/localization

#1143 Clarify overclocking tooltip in GUI
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: subsystem: gui, type: bug

#1151 Add Config Option for lossless wires damaging player
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/pipelike/cable/BlockCable.java
Labels: subsystem: cables, subsystem: config, type: feature

#1138 Feature/added replication for mold and extruder shapes in forming press
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
Labels: subsystem: recipes, type: feature

#1145 Add support custom chance functions.
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
Labels: subsystem: integration/ct, type: feature

#1125 QoL for pump cover
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/java/gregtech/common/covers/filter/FluidFilterContainer.java
  src/main/java/gregtech/common/covers/filter/FluidFilterWrapper.java
  src/main/java/gregtech/common/covers/filter/WidgetGroupFluidFilter.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: subsystem: gui, type: feature

#1142 Mark different circuit configurations as distinct subtypes in JEI.
  src/main/java/gregtech/api/recipes/ingredients/IntCircuitIngredient.java
  src/main/java/gregtech/common/items/behaviors/IntCircuitBehaviour.java
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
  src/main/java/gregtech/integration/jei/recipe/IntCircuitCategory.java
  src/main/java/gregtech/integration/jei/recipe/IntCircuitRecipeWrapper.java
  src/main/java/gregtech/integration/jei/utils/render/CompositeDrawable.java
  src/main/java/gregtech/integration/jei/utils/render/CompositeRenderer.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: status: accepted, subsystem: integration/jei, type: feature

#1159 Tickness of wires udjusted
  src/main/java/gregtech/common/pipelike/cable/Insulation.java
Labels: subsystem: cables, subsystem: render, type: bug

#1160 Bugfix/missing localization for plasma generator recipe map
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: subsystem: internationalization/localization, type: bug
