Repository GregTechCE/GregTech, pull requests merged in 2020-11, with the labels that each got.

#1284 Bugfix/item filter not persisting items if size over 127
  src/main/java/gregtech/api/util/LargeStackSizeItemStackHandler.java
  src/main/java/gregtech/common/covers/filter/SimpleItemFilter.java
Labels: status: accepted, subsystem: covers, type: bug

#1287 Feature/make granite its own material
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/loaders/OreDictionaryLoader.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: status: accepted, type: feature

#1288 Added a JEI Info Tab for the Fluid Canner Machines for Buckets and Fluid Cells
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: status: accepted, subsystem: integration/jei, type: feature

#1293 Bugfix/nether-quartz-block-to-nether-quartz-recipe-restoration
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
Labels: status: accepted, type: bug

#1297 Fixed recipe validation logging data from builder chance instead of recipe chance #1294
  src/main/java/gregtech/api/recipes/RecipeMap.java
Labels: status: accepted, type: bug

#1299 [Bugfix] : Machine controllers wrong display/config ignored
  src/main/java/gregtech/common/covers/CoverMachineController.java
Labels: status: accepted, subsystem: covers, type: bug

#1301 Bugfix/recipes progress being one tick shorter
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
Labels: status: accepted, type: bug

#1290 Better interaction with non-extractable neighbour inventories
  src/main/java/gregtech/common/inventory/itemsource/ItemSourceList.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: bug

#1319 Fix Drained Fluid Cells not stacking due to empty NBT.
  src/main/java/gregtech/api/capability/impl/SimpleThermalFluidHandlerItemStack.java
  src/main/java/gregtech/api/capability/impl/ThermalFluidHandlerItemStack.java
Labels: status: accepted, type: bug

#1317 Ensure saw-broken ice blocks don't create water.
  src/main/java/gregtech/common/tools/ToolSaw.java
Labels: status: accepted, type: bug

#1313 Multi block tank fixes
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityTank.java
Labels: status: accepted, subsystem: covers, type: bug

#1310 Integrate the Chemical Bath into the ore byproduct page. Remove extra…
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
  src/main/java/gregtech/integration/jei/recipe/primitive/OreByProduct.java
  src/main/java/gregtech/integration/jei/recipe/primitive/OreByProductCategory.java
Labels: status: accepted, subsystem: integration/jei, type: bug, type: feature

#1308 Allow Smart Filter matching to ignore required fluid inputs
  src/main/java/gregtech/api/recipes/MatchingMode.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/common/covers/filter/SmartItemFilter.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: status: accepted, subsystem: covers, type: feature

#1307 Fixed a missing command warning and a mistake in zh_cn.lang
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: status: accepted, subsystem: internationalization/localization, type: bug

#1306 Add Oredicts to granite variants, marble, basalt.
  src/main/java/gregtech/loaders/OreDictionaryLoader.java
Labels: status: accepted
