Repository GregTechCE/GregTech, pull requests merged in 2020-10, with the labels that each got.

#1260 JEI fix for getting fluids as ingredients
  src/main/java/gregtech/api/gui/impl/ModularUIGuiHandler.java
Labels: status: accepted, subsystem: integration/jei, type: bug

#1248 Allow manual I/O to bypass filters on arms/conveyors/pumps
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/java/gregtech/common/covers/ManualImportExportMode.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: subsystem: covers, type: feature

#1266 Covers on import mode take precedence over tile entity "disallow input from output side"
  src/main/java/gregtech/api/cover/CoverBehavior.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverPump.java
Labels: status: accepted, subsystem: covers, type: feature

#1267 fix: issue preventing battery from fully charged.
  src/main/java/gregtech/api/capability/impl/EnergyContainerBatteryBuffer.java
Labels: type: bug

#1274 Suggested fix for #1241
  src/main/java/gregtech/common/inventory/itemsource/NetworkItemInfo.java
Labels: status: accepted, type: bug

#1279 ru_ru.lang fixes.
  src/main/resources/assets/gregtech/lang/ru_ru.lang
Labels: status: accepted, subsystem: internationalization/localization, type: bug
