Repository GregTechCE/GregTech, pull requests merged in 2020-09, with the labels that each got.

#1258 Add NanoSaber configuration options
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/entities/EntitySpawnHandler.java
  src/main/java/gregtech/common/items/MetaItem2.java
  src/main/java/gregtech/common/items/behaviors/NanoSaberBehavior.java
Labels: status: accepted, subsystem: config, type: feature

#1240 Update Rotor Holder spinning status after world reload.
  src/main/java/gregtech/common/metatileentities/electric/multiblockpart/MetaTileEntityRotorHolder.java
Labels: status: accepted, type: bug

#1247 Fix crash when attempting to move items through Shutter Covers.
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
Labels: status: accepted, subsystem: covers, type: bug

#1232 Feature/ct material casting
  src/main/java/gregtech/api/unification/crafttweaker/CTMaterialCasting.java
Labels: subsystem: integration/ct, type: feature

#1253 Feature/add zenClass annotation to GemMaterial and RoughSolidMaterial
  src/main/java/gregtech/api/unification/material/type/GemMaterial.java
  src/main/java/gregtech/api/unification/material/type/RoughSolidMaterial.java
Labels: subsystem: integration/ct, type: feature

#1254 Feature/extend comment for config option modPriorities
  src/main/java/gregtech/common/ConfigHolder.java
Labels: subsystem: config

#1245 expose multiblock info recipe
  src/main/java/gregtech/integration/jei/multiblock/MultiblockInfoCategory.java
Labels: type: feature
