Repository GregTechCE/GregTech, pull requests merged in 2021-03, with the labels that each got.

#1467 Improved number formatting, with a couple of other fixes
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: open for discussion, status: accepted, type: feature

#1504 Progress Bar Updates
  src/main/java/gregtech/api/gui/GuiTextures.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapGroupOutput.java
  src/main/java/gregtech/common/metatileentities/steam/SteamMacerator.java
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_arrow.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_arrow_multiple.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_bath.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_bending.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_canner.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_circuit.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_compress.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_extract.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_extruder.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_hammer.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_lathe.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_macerate.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_magnet.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_mixer.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_recycler.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_sift.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_slice.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_wiremill.png
  src/main/resources/assets/gregtech/textures/gui/steam/bronze/progress_bar_bronze_macerator.png
  src/main/resources/assets/gregtech/textures/gui/steam/bronze/progress_bar_bronze_macerator_filled.png
  src/main/resources/assets/gregtech/textures/gui/steam/steel/progress_bar_steel_macerator.png
  src/main/resources/assets/gregtech/textures/gui/steam/steel/progress_bar_steel_macerator_filled.png
Labels: rsr: revision, status: accepted, type: bug

#1511 Fix the Fuelable TOP provider to do its translation on the client
  src/main/java/gregtech/api/capability/impl/FluidFuelInfo.java
  src/main/java/gregtech/api/capability/impl/ItemFuelInfo.java
  src/main/java/gregtech/integration/theoneprobe/provider/FuelableInfoProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: integration: TOP, rsr: revision, status: accepted, type: bug

#1517 Adjust the EU/t of the Rotors
  src/main/java/gregtech/loaders/oreprocessing/PartsRecipeHandler.java
Labels: rsr: revision, status: accepted, type: bug

#1518 Adjust Biome Name tooltip to use getter
  src/main/java/gregtech/integration/jei/GTOreInfo.java
Labels: rsr: revision, status: accepted, type: bug

#1520 Fix TOP Transformer Translation
  src/main/java/gregtech/integration/theoneprobe/provider/TransformerInfoProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: rsr: revision, status: accepted, type: bug

#1461 Plunger as a voiding fluid itemstack
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/capability/impl/VoidFluidHandlerItemStack.java
  src/main/java/gregtech/api/items/IToolItem.java
  src/main/java/gregtech/api/items/toolitem/ToolMetaItem.java
  src/main/java/gregtech/common/items/behaviors/PlungerBehaviour.java
Labels: rsr: revision, status: accepted, subsystem: metatools, type: feature

#1483 Add ability to set Input Allowed via the machine grid
  src/main/java/gregtech/api/capability/GregtechTileCapabilities.java
  src/main/java/gregtech/api/capability/IActiveOutputSide.java
  src/main/java/gregtech/api/capability/SimpleCapabilityManager.java
  src/main/java/gregtech/api/cover/CoverBehavior.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
Labels: rsr: revision, status: accepted, type: feature

#1492 Fixing the Chemistry, Take Two
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/loaders/recipe/ChemistryRecipes.java
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/chemistry/BrewingRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/ChemicalBathRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/ChemistryRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/CrackingRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/DistillationRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/MixerRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/ReactorRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/SeparationRecipes.java
Labels: open for discussion, release note needed, rsr: minor, status: accepted, type: bug, type: feature

#1514 Add notConsumable Fluids
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
Labels: rsr: revision, status: accepted, type: feature

#1516 Drop NBT For JEI Recipe Registration
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
Labels: integration: JEI, rsr: revision, status: accepted, type: feature

#1523 Allow using Right mouse button to cycle some widgets in reverse
  src/main/java/gregtech/api/gui/widgets/CycleButtonWidget.java
Labels: status: accepted, subsystem: gui, type: feature

#1535 Allow Stacks of Fluid Containers in Quantum Tank
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: rsr: revision, status: accepted, type: bug

#1542 Remove Duplicate Recipes
  src/main/java/gregtech/common/items/MetaItem2.java
Labels: rsr: revision, status: accepted, type: bug

#1527 made Rotor holder independant from large turbine controller
  src/main/java/gregtech/common/metatileentities/electric/multiblockpart/MetaTileEntityRotorHolder.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeTurbine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/RotorHolderMultiblockController.java
Labels: rsr: revision, status: accepted, type: feature
