Repository GregTechCE/GregTech, pull requests merged in 2021-05, with the labels that each got.

#1586 Fix EV charger not having a recipe
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
Labels: rsr: revision, status: accepted, subsystem: recipes, type: bug

#1587 Fix Steel Steam furnace not using steel pipes
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
Labels: rsr: revision, status: accepted, subsystem: recipes, type: bug

#1565 Fix git using wrong folder, upgrade jgit and gradle
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: rsr: revision, status: help needed

#1549 Fix Granite ID Shift
  src/main/java/gregtech/GregTechVersion.java
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/api/util/Version.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/asm/CompoundDataFixerGetVersionVisitor.java
  src/main/java/gregtech/common/asm/GTCETransformer.java
  src/main/java/gregtech/common/asm/SaveFormatOldLoadVisitor.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/common/blocks/modelfactories/BlockCompressedFactory.java
  src/main/java/gregtech/common/datafix/GregTechDataFixers.java
  src/main/java/gregtech/common/datafix/GregTechFixType.java
  src/main/java/gregtech/common/datafix/fixes/Fix0PostGraniteMetaBlockShift.java
  src/main/java/gregtech/common/datafix/fixes/Fix0PostGraniteMetaBlockShiftInWorld.java
  src/main/java/gregtech/common/datafix/fixes/Fix1MetaBlockIdSystem.java
  src/main/java/gregtech/common/datafix/fixes/Fix1MetaBlockIdSystemInWorld.java
  src/main/java/gregtech/common/datafix/fixes/metablockid/MetaBlockIdFixHelper.java
  src/main/java/gregtech/common/datafix/fixes/metablockid/MetaBlockIdFixer.java
  src/main/java/gregtech/common/datafix/fixes/metablockid/MetaBlockIdRemapCache.java
  src/main/java/gregtech/common/datafix/fixes/metablockid/PostGraniteMetaBlockIdFixer.java
  src/main/java/gregtech/common/datafix/fixes/metablockid/PreGraniteMetaBlockIdFixer.java
  src/main/java/gregtech/common/datafix/fixes/metablockid/WorldDataHooks.java
  src/main/java/gregtech/common/datafix/util/DataFixHelper.java
  src/main/java/gregtech/common/datafix/util/RemappedBlock.java
  src/main/java/gregtech/common/datafix/walker/WalkChunkSection.java
  src/main/java/gregtech/common/datafix/walker/WalkItemStackLike.java
  src/test/java/gregtech/common/blocks/Mapping.java
  src/test/java/gregtech/common/blocks/MetaBlocksTest.java
Labels: release note needed, rsr: minor, type: bug, type: feature

#1594 Remove Forge Multipart legacy support
  build.gradle.kts
  build.properties
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/common/pipelike/fluidpipe/net/FluidPipeNet.java
  src/main/java/gregtech/integration/multipart/CableMultiPart.java
  src/main/java/gregtech/integration/multipart/CableMultiPartTickable.java
  src/main/java/gregtech/integration/multipart/FluidPipeActiveMultiPart.java
  src/main/java/gregtech/integration/multipart/FluidPipeMultiPart.java
  src/main/java/gregtech/integration/multipart/GTMultipartFactory.java
  src/main/java/gregtech/integration/multipart/PipeMultiPart.java
Labels: rsr: minor, type: feature

#1563 Fixed Global Renderer in MetaTileEntityTESR
  src/main/java/gregtech/api/render/MetaTileEntityTESR.java
Labels: rsr: revision, status: accepted, subsystem: render, type: bug

#1579 Allow covers on chest bottoms
  src/main/java/gregtech/api/render/ChestRenderer.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityChest.java
  src/main/resources/assets/gregtech/textures/blocks/storage/metal_chest/base_front.png
  src/main/resources/assets/gregtech/textures/blocks/storage/metal_chest/base_side.png
  src/main/resources/assets/gregtech/textures/blocks/storage/wooden_chest/base_front.png
  src/main/resources/assets/gregtech/textures/blocks/storage/wooden_chest/base_side.png
Labels: rsr: revision, status: accepted, subsystem: covers, subsystem: render, type: feature

#1590 Do not spawn rubber trees in water, looks ugly
  src/main/java/gregtech/common/worldgen/WorldGenRubberTree.java
Labels: rsr: revision, status: accepted, subsystem: worldgen, type: bug

#1595 Using MetaItems using FoodStats with a Non-Null containerItem now return that ItemStack to the Player
  src/main/java/gregtech/api/items/metaitem/FoodStats.java
  src/main/java/gregtech/api/items/metaitem/FoodUseManager.java
  src/main/java/gregtech/api/items/metaitem/stats/IFoodBehavior.java
Labels: rsr: revision, status: accepted, type: bug

#1596 Fix Issues with Dust Uncrafting
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/loaders/oreprocessing/MaterialRecipeHandler.java
Labels: integration: JEI, rsr: minor, status: accepted, subsystem: recipes, type: bug

#1600 fix TOP showing wring burn time
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamCoalBoiler.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamLavaBoiler.java
Labels: integration: TOP, rsr: revision, status: accepted, type: bug

#1603 Add NotConsumable Fluids to CT
  src/main/java/gregtech/api/recipes/crafttweaker/CTRecipeBuilder.java
Labels: integration: CT, rsr: revision, status: accepted, type: feature

#1580 Rework of Recipe Properties
  .gitignore
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/builders/ArcFurnaceRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/BlastRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/CutterRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/ImplosionRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/IntCircuitRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/SimpleRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/UniversalDistillationRecipeBuilder.java
  src/main/java/gregtech/api/recipes/crafttweaker/CTRecipe.java
  src/main/java/gregtech/api/recipes/recipeproperties/BlastTemperatureProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/DefaultProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/RecipeProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/RecipePropertyStorage.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
  src/test/java/gregtech/api/recipes/recipeproperties/RecipePropertyStorageTest.java
Labels: integration: JEI, rsr: minor, status: accepted, subsystem: recipes

#1593 Feature/remove Bintray
  .gitlab-ci.yml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: rsr: revision, type: bug

#1592 Switching Hay Bale recipe from Compressor to Packager
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
Labels: rsr: minor, subsystem: recipes, type: bug

#1485 Fix wheel action in MouseTweaks and Crafting Station voiding items
  src/main/java/gregtech/api/gui/ModularUI.java
  src/main/java/gregtech/api/gui/widgets/SlotWidget.java
  src/main/java/gregtech/common/gui/widget/CraftingSlotWidget.java
  src/main/java/gregtech/common/metatileentities/storage/CraftingRecipeResolver.java
  src/main/java/gregtech/integration/jei/recipe/RecipeMapCategory.java
Labels: rsr: undefined, type: bug

#1611 Made Glass tubes more distinct in the Assembler usages
  src/main/resources/assets/gregtech/textures/gui/overlay/circuit_overlay.png
Labels: rsr: revision, status: accepted, subsystem: gui, subsystem: textures

#1612 Use TOP's item label to translate fuel item names
  src/main/java/gregtech/api/capability/impl/ItemFuelInfo.java
  src/main/java/gregtech/integration/theoneprobe/provider/FuelableInfoProvider.java
Labels: integration: TOP, rsr: revision, status: accepted, subsystem: internationalization/localization, type: bug

#1619 Miscellaneous Surface Rock updates
  src/main/java/gregtech/api/worldgen/populator/SurfaceBlockPopulator.java
  src/main/java/gregtech/api/worldgen/populator/SurfaceRockPopulator.java
  src/main/resources/assets/gregtech/worldgen/end/beryllium_vein.json
  src/main/resources/assets/gregtech/worldgen/end/lapis_vein.json
  src/main/resources/assets/gregtech/worldgen/end/manganese_vein.json
  src/main/resources/assets/gregtech/worldgen/end/molybdenum_vein.json
  src/main/resources/assets/gregtech/worldgen/end/naquadah_vein.json
  src/main/resources/assets/gregtech/worldgen/end/nickel_vein.json
  src/main/resources/assets/gregtech/worldgen/end/olivine_vein.json
  src/main/resources/assets/gregtech/worldgen/end/platinum_vein.json
  src/main/resources/assets/gregtech/worldgen/end/tungstate_vein.json
  src/main/resources/assets/gregtech/worldgen/nether/chalcopyrite_vein.json
  src/main/resources/assets/gregtech/worldgen/nether/iron_vein.json
  src/main/resources/assets/gregtech/worldgen/nether/magnetite_vein.json
  src/main/resources/assets/gregtech/worldgen/nether/netherquartz_vein.json
  src/main/resources/assets/gregtech/worldgen/nether/nickel_vein.json
  src/main/resources/assets/gregtech/worldgen/nether/redstone_vein.json
  src/main/resources/assets/gregtech/worldgen/nether/sulfur_vein.json
  src/main/resources/assets/gregtech/worldgen/nether/tetrahedrite_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/apatite_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/bauxite_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/beryllium_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/bornite_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/chalcopyrite_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/coal_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/diamond_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/galena_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/iron_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/lapis_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/lignitecoal_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/magnetite_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/manganese_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/molybdenite_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/monazite_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/nickel_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/olivine_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/pitchblende_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/platinum_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/quartz_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/redstone_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/salts_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/sapphire_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/soapstone_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/tenorite_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/tetrahedrite_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/tin_vein.json
  src/main/resources/assets/gregtech/worldgen/overworld/tungstate_vein.json
Labels: rsr: revision, status: accepted, subsystem: worldgen, type: bug, type: feature

#1620 Add recipe using liquid ice
  src/main/java/gregtech/common/MetaFluids.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
Labels: rsr: revision, status: accepted, type: feature

#1621 Fix Item Collector duplicating items
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityItemCollector.java
Labels: rsr: revision, status: accepted, type: bug

#1622 Make MatFlags Require Unique IDs
  src/main/java/gregtech/api/unification/material/type/Material.java
Labels: rsr: revision, status: accepted, type: bug

#1624 Add Active Overlay to Singleblock Steam and Gas Turbines
  src/main/resources/assets/gregtech/textures/blocks/generators/gas_turbine/overlay_side_active.png
  src/main/resources/assets/gregtech/textures/blocks/generators/gas_turbine/overlay_side_active.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/generators/steam_turbine/overlay_side_active.png
  src/main/resources/assets/gregtech/textures/blocks/generators/steam_turbine/overlay_side_active.png.mcmeta
Labels: rsr: revision, status: accepted, subsystem: textures, type: feature

#1625 Add vanilla dusts to dustRegular
  src/main/java/gregtech/api/items/materialitem/MaterialMetaItem.java
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/loaders/OreDictionaryLoader.java
Labels: rsr: revision, status: accepted, type: bug

#1626 Revert #1447
  src/main/java/gregtech/common/metatileentities/electric/multiblockpart/MetaTileEntityFluidHatch.java
Labels: integration: TOP, rsr: revision, status: accepted, type: bug

#1627 Correct the material type for plain granite ore blocks
  src/main/java/gregtech/api/unification/ore/StoneTypes.java
Labels: rsr: revision, status: accepted, type: bug

#1629 Fix items not clickable in the crafting station
  src/main/java/gregtech/api/gui/widgets/ScrollableListWidget.java
Labels: rsr: revision, status: accepted, subsystem: gui, type: bug

#1633 Add Component Assembler recipes
  src/main/java/gregtech/loaders/recipe/ComponentRecipes.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
Labels: rsr: revision, status: accepted, subsystem: recipes, type: feature

#1630 Add unique OrientedOverlayRenderers for multiblocks
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/api/render/Textures.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityLargeBoiler.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCrackingUnit.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDistillationTower.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityElectricBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityImplosionCompressor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPyrolyseOven.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityVacuumFreezer.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/FueledMultiblockController.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityDieselEngine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeTurbine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/RotorHolderMultiblockController.java
  src/main/resources/assets/gregtech/textures/blocks/multiblock/blast_furnace/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/blast_furnace/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/cracking_unit/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/cracking_unit/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/distillation_tower/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/distillation_tower/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/diesel_engine/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/diesel_engine/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_bronze_boiler/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_bronze_boiler/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_gas_turbine/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_gas_turbine/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_plasma_turbine/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_plasma_turbine/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_steam_turbine/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_steam_turbine/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_steel_boiler/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_steel_boiler/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_titanium_boiler/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_titanium_boiler/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_tungstensteel_boiler/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/generator/large_tungstensteel_boiler/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/implosion_compressor/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/implosion_compressor/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/multi_furnace/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/multi_furnace/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/pyrolyse_oven/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/pyrolyse_oven/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/vacuum_freezer/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/vacuum_freezer/overlay_front_active.png
Labels: rsr: revision, status: accepted, subsystem: render, subsystem: textures, type: feature
