Repository GregTechCE/GregTech, pull requests merged in 2021-02, with the labels that each got.

#1422 Fix Turbine Running When It Shouldn't
  src/main/java/gregtech/api/capability/impl/FuelRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/common/metatileentities/electric/multiblockpart/MetaTileEntityRotorHolder.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/LargeTurbineWorkableHandler.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeTurbine.java
Labels: rsr: revision, status: accepted, type: bug

#1432 Fix Coke Oven/PBF Overlay Textures
  src/main/resources/assets/gregtech/textures/blocks/machines/coke_oven/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/machines/coke_oven/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/machines/primitive_blast_furnace/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/machines/primitive_blast_furnace/overlay_front_active.png
Labels: rsr: revision, status: accepted, subsystem: textures, type: bug

#1435 Fix NPE When Placing Covers
  src/main/java/gregtech/api/cover/ICoverable.java
  src/main/java/gregtech/api/pipenet/tile/PipeCoverableImplementation.java
Labels: rsr: revision, status: accepted, type: bug

#1447 Fix Two Tanks in TOP for Input Hatch
  src/main/java/gregtech/common/metatileentities/electric/multiblockpart/MetaTileEntityFluidHatch.java
Labels: rsr: revision, status: accepted, type: bug

#1424 Distribute Ticks More Evenly
  src/main/java/gregtech/api/capability/impl/RecipeLogicSteam.java
  src/main/java/gregtech/api/cover/ICoverable.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SimpleGeneratorMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/TickableTileEntityBase.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/api/pipenet/tile/PipeCoverableImplementation.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityAirCollector.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityBlockBreaker.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityFisher.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityItemCollector.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityMagicEnergyAbsorber.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityPump.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityTeslaCoil.java
  src/main/java/gregtech/common/metatileentities/electric/multiblockpart/MetaTileEntityItemBus.java
  src/main/java/gregtech/common/metatileentities/electric/multiblockpart/MetaTileEntityRotorHolder.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityCokeOvenHatch.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityLargeBoiler.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: rsr: revision, status: accepted, type: feature

#1496 Adds Quality of Life Zen circuit method for adding recipes
  src/main/java/gregtech/api/recipes/crafttweaker/CTRecipeBuilder.java
Labels: integration: CT, rsr: revision, status: accepted, type: feature

#1495 Remove Duplicate Dense Plate Recipe
  src/main/java/gregtech/loaders/oreprocessing/MaterialRecipeHandler.java
Labels: rsr: revision, status: accepted, type: bug

#1494 Open Up Multiblock Overlay
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
Labels: rsr: revision, status: accepted, subsystem: textures, type: feature

#1484 Add an IFuelable capability to display fuel info in TOP
  src/main/java/gregtech/api/capability/GregtechCapabilities.java
  src/main/java/gregtech/api/capability/IFuelInfo.java
  src/main/java/gregtech/api/capability/IFuelable.java
  src/main/java/gregtech/api/capability/SimpleCapabilityManager.java
  src/main/java/gregtech/api/capability/impl/AbstractFuelInfo.java
  src/main/java/gregtech/api/capability/impl/FluidFuelInfo.java
  src/main/java/gregtech/api/capability/impl/FuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/ItemFuelInfo.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityLargeBoiler.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/LargeTurbineWorkableHandler.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamCoalBoiler.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamLavaBoiler.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeCompatibility.java
  src/main/java/gregtech/integration/theoneprobe/provider/FuelableInfoProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: integration: TOP, rsr: minor, status: accepted, type: feature

#1482 Optimize Render Bounding Box for Chest and Safe
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityLockedSafe.java
Labels: rsr: revision, status: accepted, subsystem: render, type: bug

#1481 Use material color in particle texture, optimize color convertion
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityTank.java
Labels: rsr: revision, status: accepted, subsystem: render, type: bug

#1479 Fix the caching for container items in the CraftingStation
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/InventoryUtils.java
  src/main/java/gregtech/common/metatileentities/storage/CachedRecipeData.java
Labels: rsr: revision, status: accepted, type: bug

#1478 Fix some Russian translation
  src/main/resources/assets/gregtech/lang/ru_ru.lang
Labels: rsr: revision, status: accepted, subsystem: internationalization/localization, type: bug

#1477 Sort items by amount in descending order
  src/main/java/gregtech/api/util/GTUtility.java
Labels: rsr: revision, status: accepted, type: bug

#1475 Fix chest placement render problem (Fix #1474)
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityChest.java
Labels: rsr: revision, status: accepted, subsystem: render, type: bug

#1471 Refactoring MetaTileEntityChest
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityChest.java
Labels: rsr: revision, status: accepted

#1470 Fix findPlayersUsing's usage of AxisAlignedBB
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityChest.java
Labels: rsr: revision, status: accepted, type: bug

#1466 Don't set held item for non player listeners
  src/main/java/gregtech/api/gui/impl/ModularUIContainer.java
Labels: rsr: revision, status: accepted, subsystem: gui, type: bug

#1464 Don't place the same tile multiple times for JEI multiblock rendering
  src/main/java/gregtech/integration/jei/multiblock/MultiblockShapeInfo.java
Labels: integration: JEI, rsr: revision, status: accepted, type: bug

#1463 Don't generate orebyproduct recipes when there are no byproducts fixe…
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
  src/main/java/gregtech/integration/jei/recipe/primitive/OreByProduct.java
Labels: integration: JEI, rsr: revision, status: accepted, type: bug

#1462 Allow walking over surface rocks #1455
  src/main/java/gregtech/common/blocks/surfacerock/BlockSurfaceRock.java
Labels: rsr: revision, status: accepted, subsystem: worldgen, type: feature

#1459 Add some descriptors to the machine controller
  src/main/java/gregtech/common/covers/CoverMachineController.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: rsr: revision, status: accepted, subsystem: gui, type: feature

#1452 Update JEI Multiblocks to show block counts and allow bookmarking
  src/main/java/gregtech/integration/jei/multiblock/MultiblockInfoCategory.java
  src/main/java/gregtech/integration/jei/multiblock/MultiblockInfoRecipeWrapper.java
Labels: integration: JEI, rsr: revision, status: accepted, type: feature

#1386 Add an Ore vein generation page to JEI
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/util/FileUtility.java
  src/main/java/gregtech/api/worldgen/config/OreDepositDefinition.java
  src/main/java/gregtech/api/worldgen/config/WorldConfigUtils.java
  src/main/java/gregtech/api/worldgen/config/WorldGenRegistry.java
  src/main/java/gregtech/api/worldgen/populator/FluidSpringPopulator.java
  src/main/java/gregtech/api/worldgen/populator/SurfaceBlockPopulator.java
  src/main/java/gregtech/api/worldgen/populator/SurfaceRockPopulator.java
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
  src/main/java/gregtech/integration/jei/GTOreCategory.java
  src/main/java/gregtech/integration/jei/GTOreInfo.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/worldgen/dimensions.json
Labels: integration: JEI, rsr: revision, status: accepted, type: feature

#1434 Formatting proposal
  .editorconfig
Labels: open for discussion
