Repository GregTechCE/GregTech, pull requests merged in 2021-01, with the labels that each got.

#1382 Add JUnit 4 Support
  build.gradle.kts
  src/test/java/gregtech/api/util/InventoryUtilsTest.java
Labels: status: accepted

#1348 Fix incorrect Lapotron Crystal crafting recipe
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/api/util/ShapedOreEnergyTransferRecipe.java
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
Labels: status: accepted, type: bug

#1351 Fix the Primitive Blast Furnace Voiding outputs
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveBlastFurnace.java
Labels: status: accepted, type: bug

#1353 Streamlining FuelRecipeMap to be like RecipeMap
  src/main/java/gregtech/api/recipes/machines/FuelRecipeMap.java
Labels: status: accepted, subsystem: integration/ct

#1354 Fall through instead of returning null in traceCoverSide
  src/main/java/gregtech/api/cover/ICoverable.java
Labels: status: accepted, subsystem: covers

#1355 Fix large boiler heatEfficiencyMultiplier
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityLargeBoiler.java
Labels: status: accepted, type: bug

#1362 Check all inputs to the Furnace recipe map
  src/main/java/gregtech/api/recipes/machines/RecipeMapFurnace.java
Labels: status: accepted, type: bug

#1369 Fix wood recipes detection
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/loaders/recipe/WoodMachineRecipes.java
Labels: status: accepted, type: bug

#1372 Fix Forge data and Capabilities not being synced to client.
  src/main/java/gregtech/api/metatileentity/SyncedTileEntityBase.java
Labels: status: accepted, type: bug

#1373 fixCCLErrors
  src/main/java/gregtech/common/render/ShapeModelGenerator.java
  src/main/java/gregtech/common/render/StonePileModelGenerator.java
Labels: status: accepted, subsystem: render, type: bug

#1384 Fix Logic Bugs and Improve Utility of Multiblock Voiding Fix Code
  src/main/java/gregtech/api/util/InventoryUtils.java
  src/main/java/gregtech/api/util/ItemStackHashStrategy.java
  src/main/java/gregtech/api/util/Predicates.java
  src/main/java/gregtech/api/util/StreamUtils.java
  src/test/java/gregtech/api/util/InventoryUtilsTest.java
Labels: status: accepted, type: bug

#1388 Remove Extra Fuel recipe additions
  src/main/java/gregtech/loaders/recipe/FuelRecipes.java
Labels: status: accepted, type: bug

#1400 Tehnut's maven removed as it is not needed
  build.gradle.kts
Labels: status: accepted

#1428 Allow Fluid to be Plasma and Placeable
  src/main/java/gregtech/common/MetaFluids.java
Labels: rsr: revision, status: accepted, type: bug

#1427 Take Fluids Out Of Input Hatch
  src/main/java/gregtech/common/metatileentities/electric/multiblockpart/MetaTileEntityFluidHatch.java
Labels: rsr: revision, status: accepted, type: feature

#1421 Fixes #1085
  src/main/java/gregtech/common/CommonProxy.java
Labels: rsr: revision, status: accepted, type: bug

#1420 Fixes #1365
  src/main/java/gregtech/api/worldgen/populator/SurfaceRockPopulator.java
Labels: rsr: revision, status: accepted, type: bug

#1419 Bugfix/metal rods duplicated recipes in extruder
  src/main/java/gregtech/loaders/oreprocessing/PartsRecipeHandler.java
Labels: rsr: revision, status: accepted, subsystem: recipes, type: bug

#1418 Make oregen check local chunk coordinates instead of origin corners
  src/main/java/gregtech/api/worldgen/generator/CachedGridEntry.java
Labels: rsr: revision, status: accepted, subsystem: worldgen, type: bug

#1416 Add "Regular" to dust oredict entries
  src/main/java/gregtech/api/items/materialitem/MaterialMetaItem.java
  src/main/java/gregtech/api/unification/OreDictUnifier.java
Labels: rsr: revision, status: accepted, type: feature

#1415 Fix Tooltip Bounding Box
  src/main/java/gregtech/api/gui/Widget.java
Labels: rsr: revision, status: accepted, type: bug

#1413 Fixing duplicate recipes for seed oil
  src/main/java/gregtech/loaders/recipe/ChemistryRecipes.java
Labels: rsr: revision, status: accepted, subsystem: recipes, type: bug

#1408 Rotor Mold
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/loaders/oreprocessing/PartsRecipeHandler.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.rotor.json
  src/main/resources/assets/gregtech/recipes/shape/mold/shape_mold_rotor.json
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.rotor.png
Labels: release note needed, rsr: minor, status: accepted, subsystem: recipes, type: feature

#1405 Add Cable Recipes and 4x Cable/Wire Recipes
  src/main/java/gregtech/loaders/oreprocessing/WireRecipeHandler.java
Labels: rsr: revision, status: accepted, type: feature

#1404 Add Better TOP Transformer Info
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeCompatibility.java
  src/main/java/gregtech/integration/theoneprobe/provider/TransformerInfoProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: integration: TOP, rsr: revision, status: accepted, type: feature

#1394 Bug fix for ItemHandlerList::extractItem
  src/main/java/gregtech/api/capability/impl/ItemHandlerList.java
Labels: rsr: revision, status: accepted, type: bug

#1387 Make InputIngredient implement IIngredient
  src/main/java/gregtech/api/recipes/crafttweaker/InputIngredient.java
Labels: integration: CT, rsr: revision, status: accepted, type: feature

#1352 Getting generated MetaItem's as an IItemStack
  src/main/java/gregtech/api/items/materialitem/MaterialMetaItem.java
  src/main/java/gregtech/api/recipes/crafttweaker/MetaItemBracketHandler.java
  src/main/java/gregtech/common/CommonProxy.java
Labels: integration: CT, rsr: revision, status: accepted

#1414 Fixing the Chemistry
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/loaders/oreprocessing/DecompositionRecipeHandler.java
  src/main/java/gregtech/loaders/oreprocessing/OreRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/ChemistryRecipes.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: release note needed, rsr: minor, type: bug, type: feature
